from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"


module reads_workflow:
    snakefile:
        github("cuspuk/workflow_reads", path="workflow/Snakefile", tag="v3.4.5") # NOTE this should stay frozen to prevent breaking changes of python 3.11 in HPC
    config:
        config


use rule * from reads_workflow exclude all, multiqc__report


dynamic_outputs = reads_workflow.get_outputs()


include: "rules/mapping.smk"
include: "rules/freyja.smk"
include: "rules/result.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_outputs(),
        **dynamic_outputs,
    localrule: True
