from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"


module reads_workflow:
    snakefile:
        github("xsitarcik/reads", path="workflow/Snakefile", tag="v3.1.7")
    config:
        config


use rule * from reads_workflow exclude all


dynamic_outputs = reads_workflow.get_outputs()


include: "rules/mapping.smk"
include: "rules/freyja.smk"
include: "rules/result.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_outputs(),
        **dynamic_outputs,
    localrule: True
