"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/WastewaterCovid"
definitions:
  WastewaterCovid:
    type: object
    additionalProperties: true
    properties:
      pepfile:
        type: string
        description: "Path to the PEP file containing the info how to load the data"
        default: "config/pep/config.yaml"
      mapping_ref:
        type: string
        description: "Directory with reference fasta file used to map input reads"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs"
        default: 1
        Minimum: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job"
        Minimum: 2048
        default: 2048
      freyja__params:
        type: object
        "$ref": "#/definitions/FreyjaParams"
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
    required:
      - pepfile
      - mapping_ref
      - threads
      - resources
      - freyja__params
    title: WastewaterCovid
  FreyjaParams:
    type: object
    additionalProperties: false
    properties:
      lineages_dir:
        type: string
        description: "Directory with lineages to infer variants"
      depth_cutoff:
        type: integer
        description: "exclude sites with coverage less than the specified value"
        default: 0
        Minimum: 0
      min_lineage_abundance:
        type: number
        description: "the minimum lineage abundance returned to the user"
        default: 0
        Minimum: 0
      only_confirmed_lineages:
        type: boolean
        description: "use only lineages that are flagged as confirmed"
        default: true
    title: FreyjaParams
  Resources:
    bam_index_mem_mb:
      type: integer
      description: "Memory in MB to reserve for bam_index"
    picard_mem_mb:
      type: integer
      description: "Memory in MB to reserve for picard"
    qualimap_mem_mb:
      type: integer
      description: "Memory in MB to reserve for qualimap"
    title: Resources
    required:
      - bam_index_mem_mb
      - picard_mem_mb
      - qualimap_mem_mb
  Threads:
    mapping:
      type: integer
      default: 1
      description: "Number of threads to use for mapping"
    bam_index:
      type: integer
      default: 1
      description: "Number of threads to use for bam_index"
    title: Threads
    required:
      - mapping
      - bam_index
